
export const CLIENT_PORT = 6173;
export const SERVER_PORT = 5001;

export const SPORTS: string[] = [
    'Baseball',
    'Basketball',
    'Boxing',
    'Chess',
    'Cricket',
    'Football',
    'Golf',
    'Hockey',
    'Rugby',
    'Soccer',
    'Tennis',
    'MMA'
]

export const Status = {
    Success: 201,
    DeleteSuccess: 204,
    NotFound: 404,
    Failure: 409,
    Error: 400
};

export const allSportsbooks: string[] = [
    "10bet",
    "5Dimes",
    "888sport",
    "888sport (Canada)",
    "Action 24/7",
    'Bally Bet',
    "Barstool",
    "bet365",
    'BET99',
    "Bet America",
    "BetAnySports",
    'Betcris',
    "BetDSI",
    "Betfair",
    "Betfair Exchange",
    "Betfred",
    "BetMGM",
    "BetOnline",
    "betPARX",
    "Bet Right",
    "BetRivers",
    "BetRivers (Ontario)",
    "Betsafe",
    "Betsson",
    "Betstar",
    'BetUS',
    'Betway',
    "Betway (Arizona)",
    "Betway (Canada)",
    "Betway (Virginia)",
    "BetWildwood",
    "BlueBet",
    "Bodog",
    "BookMaker",
    "BookMaker.com.au",
    "BoomBet",
    "Borgota",
    "Bovada",
    "bwin",
    "Caesars",
    "Caesars (Tennesee)",
    "Casumo",
    'Circa Sports',
    'Circa Vegas',
    "ComeOn!",
    "Coolbet",
    "DraftKings",
    'DraftKings (Tennesee)',
    "DRF",
    'Elite Sportsbook',
    "Everygame",
    'FanDuel',
    'Four Winds',
    'FOX Bet',
    'Fubo',
    'Golden Nugget',
    'Hard Rock',
    'Hard Rock (Arizona)',
    'Hard Rock (Virginia)',
    'Heritage',
    'Intertops',
    'Ladbrokes',
    'Ladbrokes (Australia)',
    'LeoVegas',
    'MaximBet',
    'Monkey Knife Fight',
    'Mr Green',
    'MyBookie',
    'Neds',
    'Nitrogen',
    'NorthStar Bets',
    "OddsJam",
    'Palmerbet',
    'ParlayPlay',
    'partypoker',
    'Pinnacle',
    'PlayUp',
    'PlayUp (Australia)',
    'PointsBet',
    'PointsBet (Australia)',
    'PointsBet (Colorado)',
    'PointsBet (Illinois)',
    'PointsBet (Indiana)',
    'PointsBet (Indiana)',
    'PointsBet (Iowa)',
    'PointsBet (Michigan)',
    'PointsBet (New Jersey)',
    'PointsBet (Ontario)',
    'PointsBet (Pennsylvania)',
    'PointsBet (Virginia)',
    'PointsBet (West Virginia)',
    'PrizePicks',
    'PrizePicks (5 Flex)',
    'Proline',
    'Prophet Exchange',
    'Resorts',
    'resorts World Bet',
    'Rivalry',
    'SBK',
    'SI',
    'Spin Sports',
    'Sportsbet',
    'Sportsbetting.ag',
    'Sportsbeeting.com',
    'Sports Interaction',
    'Stake',
    'SugarHouse',
    'SuperBook',
    'Suprabets',
    'TAB',
    'theScore',
    'Thrive Fantasy',
    'Tipico',
    'TonyBet',
    'TwinSpires',
    'Underdog Fantasy',
    "Underdog Fantasy (5 Pick)",
    "Unibet",
    "Unibet (Australia)",
    "Westgate",
    'William Hill',
    'William Hill (Europe)',
    'Wind Creek',
    'WynnBET',
    'WynnBET (Michigan)',
    'Xbet'
]

export const prunedSportsbooks: string[] = [
    "888sport",
    "888sport (Canada)",
    "Action 24/7",
    'Bally Bet',
    "Barstool",
    "bet365",
    'BET99',
    "Betfair",
    "Betfair Exchange",
    "Betfred",
    "BetMGM",
    "BetOnline",
    "betPARX",
    "Bet Right",
    "BetRivers",
    "BetRivers (Ontario)",
    "Betsafe",
    "Betsson",
    "Betstar",
    'Betway',
    "Betway (Arizona)",
    "Betway (Canada)",
    "Betway (Virginia)",
    "BetWildwood",
    "BlueBet",
    "Bodog",
    "BookMaker.com.au",
    "BoomBet",
    "Borgota",
    "Bovada",
    "bwin",
    "Caesars",
    "Caesars (Tennesee)",
    "Casumo",
    'Circa Sports',
    'Circa Vegas',
    "ComeOn!",
    "Coolbet",
    "DraftKings",
    'DraftKings (Tennesee)',
    "DRF",
    'Elite Sportsbook',
    'FanDuel',
    'Four Winds',
    'FOX Bet',
    'Golden Nugget',
    'Hard Rock',
    'Hard Rock (Arizona)',
    'Hard Rock (Virginia)',
    'Ladbrokes',
    'Ladbrokes (Australia)',
    'Monkey Knife Fight',
    'NorthStar Bets',
    "OddsJam",
    'Palmerbet',
    'ParlayPlay',
    'partypoker',
    'Pinnacle',
    'PlayUp',
    'PlayUp (Australia)',
    'PointsBet',
    'PointsBet (Australia)',
    'PointsBet (Colorado)',
    'PointsBet (Illinois)',
    'PointsBet (Indiana)',
    'PointsBet (Indiana)',
    'PointsBet (Iowa)',
    'PointsBet (Michigan)',
    'PointsBet (New Jersey)',
    'PointsBet (Ontario)',
    'PointsBet (Pennsylvania)',
    'PointsBet (Virginia)',
    'PointsBet (West Virginia)',
    'PrizePicks',
    'PrizePicks (5 Flex)',
    'Proline',
    'Prophet Exchange',
    'Resorts',
    'resorts World Bet',
    'SBK',
    'SI',
    'Spin Sports',
    'Sportsbet',
    'Sportsbetting.ag',
    'Sports Interaction',
    'Stake',
    'SugarHouse',
    'SuperBook',
    'Suprabets',
    'TAB',
    'theScore',
    'Tipico',
    'TwinSpires',
    'Underdog Fantasy',
    "Underdog Fantasy (5 Pick)",
    "Unibet",
    "Unibet (Australia)",
    "Westgate",
    'William Hill',
    'William Hill (Europe)',
    'Wind Creek',
    'WynnBET',
    'WynnBET (Michigan)'
]

export const coPlusSportsbooks: string[] = [
    'Bally Bet',
    "bet365",
    "Betfair",
    "Betfair Exchange",
    "Betfred",
    "BetMGM",
    "BetRivers",
    "Betsafe",
    "Betsson",
    'Betway',
    "Bovada",
    "Caesars",
    'Circa Sports',
    "DraftKings",
    'Elite Sportsbook',
    'FanDuel',
    'FOX Bet',
    'Monkey Knife Fight',
    "OddsJam",
    'Pinnacle',
    'PlayUp',
    'PointsBet (Colorado)',
    'SI',
    'SugarHouse',
    'SuperBook',
    'Tipico',
    'WynnBET'
]